# Generated by Django 4.2.4 on 2023-11-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('element', models.CharField(choices=[('E', 'E'), ('I', 'I'), ('N', 'N'), ('S', 'S'), ('T', 'T'), ('F', 'F'), ('J', 'J'), ('P', 'P')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('mbti', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('info', models.TextField()),
                ('etc', models.TextField()),
                ('location', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('popup_image', models.ImageField(blank=True, null=True, upload_to='popup_store_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question'),
        ),
    ]
